name: weekly-train
on:
  schedule:
    - cron: "0 14 * * TUE"   # Tue 10:00 ET (14:00 UTC)
  workflow_dispatch:         # lets you run it manually from Actions tab

permissions:
  contents: write            # allow the workflow to push back trained models

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build training tables (ETL)
        run: python etl_build_history.py

      - name: Train regression models
        run: python train_models_regression.py

      - name: Commit models and data
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add models/*.joblib models/*.json data/train_*.parquet || true
          git commit -m "weekly retrain" || true
          git push
